// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Transfermarkt.Data;

#nullable disable

namespace My_Transfermarkt_Infastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240318130630_seedCountries")]
    partial class seedCountries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "7999c8c6-5a1c-4613-9de2-50c8bc14eced",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2c93174e-3b0e-446f-86af-883d56fr7210",
                            ConcurrencyStamp = "cf051911-8863-46b4-88a1-b22aa3a7f83b",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "4t67567e-5f7e-446f-88fa-441f56fr8700",
                            ConcurrencyStamp = "d5ea168c-4c6b-41ed-bdc8-a348d80a54c4",
                            Name = "Agent",
                            NormalizedName = "AGENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.AgentsFootballers", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FootballerId")
                        .HasColumnType("int");

                    b.HasKey("AgentId", "FootballerId");

                    b.HasIndex("FootballerId");

                    b.ToTable("AgentsFootballers");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan",
                            ShortName = "AF"
                        },
                        new
                        {
                            Id = 2,
                            Name = "land Islands",
                            ShortName = "AX"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albania",
                            ShortName = "AL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Algeria",
                            ShortName = "DZ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "American Samoa",
                            ShortName = "AS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AndorrA",
                            ShortName = "AD"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Angola",
                            ShortName = "AO"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anguilla",
                            ShortName = "AI"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antarctica",
                            ShortName = "AQ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Antigua and Barbuda",
                            ShortName = "AG"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Argentina",
                            ShortName = "AR"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Armenia",
                            ShortName = "AM"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Aruba",
                            ShortName = "AW"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Australia",
                            ShortName = "AU"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Austria",
                            ShortName = "AT"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Azerbaijan",
                            ShortName = "AZ"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bahamas",
                            ShortName = "BS"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bahrain",
                            ShortName = "BH"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bangladesh",
                            ShortName = "BD"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Barbados",
                            ShortName = "BB"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Belarus",
                            ShortName = "BY"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Belgium",
                            ShortName = "BE"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Belize",
                            ShortName = "BZ"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Benin",
                            ShortName = "BJ"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Bermuda",
                            ShortName = "BM"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bhutan",
                            ShortName = "BT"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bolivia",
                            ShortName = "BO"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bosnia and Herzegovina",
                            ShortName = "BA"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Botswana",
                            ShortName = "BW"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Bouvet Island",
                            ShortName = "BV"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Brazil",
                            ShortName = "BR"
                        },
                        new
                        {
                            Id = 32,
                            Name = "British Indian Ocean Territory",
                            ShortName = "IO"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Brunei Darussalam",
                            ShortName = "BN"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Bulgaria",
                            ShortName = "BG"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Burkina Faso",
                            ShortName = "BF"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Burundi",
                            ShortName = "BI"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cambodia",
                            ShortName = "KH"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cameroon",
                            ShortName = "CM"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Canada",
                            ShortName = "CA"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cape Verde",
                            ShortName = "CV"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Cayman Islands",
                            ShortName = "KY"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Central African Republic",
                            ShortName = "CF"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Chad",
                            ShortName = "TD"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chile",
                            ShortName = "CL"
                        },
                        new
                        {
                            Id = 45,
                            Name = "China",
                            ShortName = "CN"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Christmas Island",
                            ShortName = "CX"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Cocos (Keeling) Islands",
                            ShortName = "CC"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Colombia",
                            ShortName = "CO"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Comoros",
                            ShortName = "KM"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Congo",
                            ShortName = "CG"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Congo The Democratic Republic",
                            ShortName = "CD"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Cook Islands",
                            ShortName = "CK"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Costa Rica",
                            ShortName = "CR"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Cote D\"Ivoire",
                            ShortName = "CI"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Croatia",
                            ShortName = "HR"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Cuba",
                            ShortName = "CU"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Cyprus",
                            ShortName = "CY"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Czech Republic",
                            ShortName = "CZ"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Denmark",
                            ShortName = "DK"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Djibouti",
                            ShortName = "DJ"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Dominica",
                            ShortName = "DM"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Dominican Republic",
                            ShortName = "DO"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Ecuador",
                            ShortName = "EC"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Egypt",
                            ShortName = "EG"
                        },
                        new
                        {
                            Id = 65,
                            Name = "El Salvador",
                            ShortName = "SV"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Equatorial Guinea",
                            ShortName = "GQ"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Eritrea",
                            ShortName = "ER"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Estonia",
                            ShortName = "EE"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Ethiopia",
                            ShortName = "ET"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Falkland Islands",
                            ShortName = "FK"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Faroe Islands",
                            ShortName = "FO"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Fiji",
                            ShortName = "FJ"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Finland",
                            ShortName = "FI"
                        },
                        new
                        {
                            Id = 74,
                            Name = "France",
                            ShortName = "FR"
                        },
                        new
                        {
                            Id = 75,
                            Name = "French Guiana",
                            ShortName = "GF"
                        },
                        new
                        {
                            Id = 76,
                            Name = "French Polynesia",
                            ShortName = "PF"
                        },
                        new
                        {
                            Id = 77,
                            Name = "French Southern Territories",
                            ShortName = "TF"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Gabon",
                            ShortName = "GA"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Gambia",
                            ShortName = "GM"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Georgia",
                            ShortName = "GE"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Germany",
                            ShortName = "DE"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ghana",
                            ShortName = "GH"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Gibraltar",
                            ShortName = "GI"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Greece",
                            ShortName = "GR"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Greenland",
                            ShortName = "GL"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Grenada",
                            ShortName = "GD"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Guadeloupe",
                            ShortName = "GP"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Guam",
                            ShortName = "GU"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Guatemala",
                            ShortName = "GT"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Guernsey",
                            ShortName = "GG"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Guinea",
                            ShortName = "GN"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Guinea-Bissau",
                            ShortName = "GW"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Guyana",
                            ShortName = "GY"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Haiti",
                            ShortName = "HT"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Heard Island and Mcdonald Islands",
                            ShortName = "HM"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Vatican State",
                            ShortName = "VA"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Honduras",
                            ShortName = "HN"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Hong Kong",
                            ShortName = "HK"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Hungary",
                            ShortName = "HU"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Iceland",
                            ShortName = "IS"
                        },
                        new
                        {
                            Id = 101,
                            Name = "India",
                            ShortName = "IN"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Indonesia",
                            ShortName = "ID"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Iran Islamic Republic",
                            ShortName = "IR"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Iraq",
                            ShortName = "IQ"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Ireland",
                            ShortName = "IE"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Isle of Man",
                            ShortName = "IM"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Israel",
                            ShortName = "IL"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Italy",
                            ShortName = "IT"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Jamaica",
                            ShortName = "JM"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Japan",
                            ShortName = "JP"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Jersey",
                            ShortName = "JE"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Jordan",
                            ShortName = "JO"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Kazakhstan",
                            ShortName = "KZ"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Kenya",
                            ShortName = "KE"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Kiribati",
                            ShortName = "KI"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Korea, Democratic Republic",
                            ShortName = "KP"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Korea, Republic of",
                            ShortName = "KR"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Kuwait",
                            ShortName = "KW"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Kyrgyzstan",
                            ShortName = "KG"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Lao Democratic Republic",
                            ShortName = "LA"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Latvia",
                            ShortName = "LV"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Lebanon",
                            ShortName = "LB"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Lesotho",
                            ShortName = "LS"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Liberia",
                            ShortName = "LR"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Libyan Arab Jamahiriya",
                            ShortName = "LY"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Liechtenstein",
                            ShortName = "LI"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Lithuania",
                            ShortName = "LT"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Luxembourg",
                            ShortName = "LU"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Macao",
                            ShortName = "MO"
                        },
                        new
                        {
                            Id = 130,
                            Name = "North Macedonia",
                            ShortName = "MK"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Madagascar",
                            ShortName = "MG"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Malawi",
                            ShortName = "MW"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Malaysia",
                            ShortName = "MY"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Maldives",
                            ShortName = "MV"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Mali",
                            ShortName = "ML"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Malta",
                            ShortName = "MT"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Marshall Islands",
                            ShortName = "MH"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Martinique",
                            ShortName = "MQ"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Mauritania",
                            ShortName = "MR"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Mauritius",
                            ShortName = "MU"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Mayotte",
                            ShortName = "YT"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Mexico",
                            ShortName = "MX"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Micronesia Federated States",
                            ShortName = "FM"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Moldova, Republic of",
                            ShortName = "MD"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Monaco",
                            ShortName = "MC"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Mongolia",
                            ShortName = "MN"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Montenegro",
                            ShortName = "ME"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Montserrat",
                            ShortName = "MS"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Morocco",
                            ShortName = "MA"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Mozambique",
                            ShortName = "MZ"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Myanmar",
                            ShortName = "MM"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Namibia",
                            ShortName = "NA"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Nauru",
                            ShortName = "NR"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Nepal",
                            ShortName = "NP"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Netherlands",
                            ShortName = "NL"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Netherlands Antilles",
                            ShortName = "AN"
                        },
                        new
                        {
                            Id = 157,
                            Name = "New Caledonia",
                            ShortName = "NC"
                        },
                        new
                        {
                            Id = 158,
                            Name = "New Zealand",
                            ShortName = "NZ"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Nicaragua",
                            ShortName = "NI"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Niger",
                            ShortName = "NE"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Nigeria",
                            ShortName = "NG"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Niue",
                            ShortName = "NU"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Norfolk Island",
                            ShortName = "NF"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Northern Mariana Islands",
                            ShortName = "MP"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Norway",
                            ShortName = "NO"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Oman",
                            ShortName = "OM"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Pakistan",
                            ShortName = "PK"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Palau",
                            ShortName = "PW"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Palestinian Territory, Occupied",
                            ShortName = "PS"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Panama",
                            ShortName = "PA"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Papua New Guinea",
                            ShortName = "PG"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Paraguay",
                            ShortName = "PY"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Peru",
                            ShortName = "PE"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Philippines",
                            ShortName = "PH"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Pitcairn",
                            ShortName = "PN"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Poland",
                            ShortName = "PL"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Portugal",
                            ShortName = "PT"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Puerto Rico",
                            ShortName = "PR"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Qatar",
                            ShortName = "QA"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Reunion",
                            ShortName = "RE"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Romania",
                            ShortName = "RO"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Russian Federation",
                            ShortName = "RU"
                        },
                        new
                        {
                            Id = 183,
                            Name = "RWANDA",
                            ShortName = "RW"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Saint Helena",
                            ShortName = "SH"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Saint Kitts and Nevis",
                            ShortName = "KN"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Saint Lucia",
                            ShortName = "LC"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Saint Pierre and Miquelon",
                            ShortName = "PM"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Saint Vincent and the Grenadines",
                            ShortName = "VC"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Samoa",
                            ShortName = "WS"
                        },
                        new
                        {
                            Id = 190,
                            Name = "San Marino",
                            ShortName = "SM"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Sao Tome and Principe",
                            ShortName = "ST"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Saudi Arabia",
                            ShortName = "SA"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Senegal",
                            ShortName = "SN"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Serbia",
                            ShortName = "RS"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Seychelles",
                            ShortName = "SC"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Sierra Leone",
                            ShortName = "SL"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Singapore",
                            ShortName = "SG"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Slovakia",
                            ShortName = "SK"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Slovenia",
                            ShortName = "SI"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Solomon Islands",
                            ShortName = "SB"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Somalia",
                            ShortName = "SO"
                        },
                        new
                        {
                            Id = 202,
                            Name = "South Africa",
                            ShortName = "ZA"
                        },
                        new
                        {
                            Id = 203,
                            Name = "South Georgia",
                            ShortName = "GS"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Spain",
                            ShortName = "ES"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Sri Lanka",
                            ShortName = "LK"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Sudan",
                            ShortName = "SD"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Suriname",
                            ShortName = "SR"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Svalbard and Jan Mayen",
                            ShortName = "SJ"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Swaziland",
                            ShortName = "SZ"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Sweden",
                            ShortName = "SE"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Switzerland",
                            ShortName = "CH"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Syrian Arab Republic",
                            ShortName = "SY"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Taiwan",
                            ShortName = "TW"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Tajikistan",
                            ShortName = "TJ"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Tanzania United Republic of",
                            ShortName = "TZ"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Thailand",
                            ShortName = "TH"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Timor Leste",
                            ShortName = "TL"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Togo",
                            ShortName = "TG"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Tokelau",
                            ShortName = "TK"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Tonga",
                            ShortName = "TO"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Trinidad and Tobago",
                            ShortName = "TT"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Tunisia",
                            ShortName = "TN"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Turkey",
                            ShortName = "TR"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Turkmenistan",
                            ShortName = "TM"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Turks and Caicos Islands",
                            ShortName = "TC"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Tuvalu",
                            ShortName = "TV"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Uganda",
                            ShortName = "UG"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Ukraine",
                            ShortName = "UA"
                        },
                        new
                        {
                            Id = 229,
                            Name = "United Arab Emirates",
                            ShortName = "AE"
                        },
                        new
                        {
                            Id = 230,
                            Name = "United Kingdom",
                            ShortName = "GB"
                        },
                        new
                        {
                            Id = 231,
                            Name = "United States",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 232,
                            Name = "United States Minor Outlying Islands",
                            ShortName = "UM"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Uruguay",
                            ShortName = "UY"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Uzbekistan",
                            ShortName = "UZ"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Vanuatu",
                            ShortName = "VU"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Venezuela",
                            ShortName = "VE"
                        },
                        new
                        {
                            Id = 237,
                            Name = "Viet Nam",
                            ShortName = "VN"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Virgin Islands British",
                            ShortName = "VG"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Virgin Islands, US",
                            ShortName = "VI"
                        },
                        new
                        {
                            Id = 240,
                            Name = "Wallis and Futuna",
                            ShortName = "WF"
                        },
                        new
                        {
                            Id = 241,
                            Name = "Western Sahara",
                            ShortName = "EH"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Yemen",
                            ShortName = "YE"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Zambia",
                            ShortName = "ZM"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Zimbabwe",
                            ShortName = "ZW"
                        });
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Footballer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentMarketValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDateContract")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<decimal>("HighestValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HishestValueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternationalCaps")
                        .HasColumnType("int");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("PreferedFoot")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDateContract")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CountryId");

                    b.HasIndex("TeamId");

                    b.ToTable("Footballers");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Build")
                        .HasColumnType("datetime2");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("FootballerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("FootballerId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.TeamsFootballers", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("FootballerId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "FootballerId");

                    b.HasIndex("FootballerId");

                    b.ToTable("TeamsFootballers");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Agent", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.AgentsFootballers", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Agent", "Agent")
                        .WithMany("AgentFootballers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Footballer", "Footballer")
                        .WithMany("AgentsFootballers")
                        .HasForeignKey("FootballerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Footballer");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Footballer", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Agent");

                    b.Navigation("Country");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Stadium", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Team", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Footballer", null)
                        .WithMany("TeamsPlayed")
                        .HasForeignKey("FootballerId");

                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId");

                    b.Navigation("Country");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.TeamsFootballers", b =>
                {
                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Footballer", "Footballer")
                        .WithMany("TeamFootballers")
                        .HasForeignKey("FootballerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My_Transfermarkt_Infastructure.DataModels.Team", "Team")
                        .WithMany("TeamFootballers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Footballer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Agent", b =>
                {
                    b.Navigation("AgentFootballers");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Footballer", b =>
                {
                    b.Navigation("AgentsFootballers");

                    b.Navigation("TeamFootballers");

                    b.Navigation("TeamsPlayed");
                });

            modelBuilder.Entity("My_Transfermarkt_Infastructure.DataModels.Team", b =>
                {
                    b.Navigation("TeamFootballers");
                });
#pragma warning restore 612, 618
        }
    }
}
